baseurl = "https://hoddb.org/"
languageCode = "en-us"
metadataformat = "yaml"
title = "HodDB"
theme = "hugo-alabaster-theme"
PygmentsCodeFences = true
PygmentsStyle = "vs"
PygmentsOptions = "linenos=table"

[params]
	name = "HodDB"
	description = "A metadata schema for buildings"

	github_user   = "gtfierro"
	github_repo   = "hod"
	github_banner = true

	custom_css = []
	custom_js  = []

	highlightjs = "css/highlight.css"
	favicon = "favicon.ico"

[params.sidebar]
	logo = "favicon.ico"


	github_button  = true
	travis_button  = false
	codecov_button = false
	gratipay = ""

	show_relations = true

[params.footer]
	copyright = ""
	show_powered_by = true
